# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170207_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='weight_field',
            new_name='width_field',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
    ]
